name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run:  npx @techdocs/cli generate --source-dir ${{ github.workspace }}~/GitRepos/tap-catalog --output-dir ./site
      - run:  npx @techdocs/cli publish --publisher-type awsS3 --storage-name dbb-tapgui-techdocs-bucket --entity default/Component/spring-petclinic --directory ./site