name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies and Generate docs
        run:  npx @techdocs/cli generate --source-dir ${{ github.workspace }} --output-dir ./site
      - name: Upload docs
        env:
          AWS_REGION: ${{ secrets.REG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SAK }}
        run:  npx @techdocs/cli publish --publisher-type awsS3 --storage-name ${{ secrets.BUCKET }} --entity default/Component/spring-petclinic --directory ./site